### ISSUE TITLE
No mdata with Canon EOS RP image files

### ISSUE THREAD

**Issue by seblanc** [lclevy/canon_cr3#13]
Hi,
I have a Canon EOS RP with which I shoot in RAW, and I would like to parse the raw data into a Python usable format.

Using the canon_cr3 lib, I'm not able to parse any data from mdat. Only preview_image (PRVW) returns me the downscaled jpeg image.

```python
from canon_cr3 import Image
from canon_cr3 import CmtdData

image = 'IMG_0023.CR3'
img = Image(image)

print(len(img.preview_image)) # in PRVW
print(len(img.jpeg_image)) # trak1 of mdat
print(len(img.sd_crx_image)) # trak2 of mdat
print(len(img.hd_crx_image)) # trak3 of mdat
```

result:

```python
92820
0
0
0
```

Here is a CR3 file taken with my Canon EOS RP: https://drive.google.com/file/d/1a__2VVyz1q2RhwYsGx9b5myo_ebYVfM4/view?usp=sharing

Any help on that would be much appreciated!

**Comment by lclevy** [comment]
use https://github.com/lclevy/canon_cr3/blob/master/parse_cr3.py instead with extract flag. the Lib version is not finished. crx data can not be uncompressed by my tool as compression scheme is unknown.

**Comment by seblanc** [comment]
Thank you for your answer. 

Surprisingly, using the sample images on this repository (e.g. samples/IMG_0482_raw.CR3), I can extract some data in the mdat. It seems that the samples were taken with a Canon EOS R and not RP.

**Comment by lclevy** [comment]
Ok, i'll check that

**Comment by lclevy** [comment]
should be fixed now

**Comment by seblanc** [comment]
Hi Laurent,
Thank you for the update. May I suggest the following correction:

```python
def stsz(self, d, l, depth):
        version = self.get_long_be(d, 0)
        if l==0x14:
          size = self.get_long_be(d, 4)
          count = self.get_long_be(d, 8)
        else:  #0x18
          size = self.get_long_be(d, 12)
          count = self.get_long_be(d, 8)
        return size
```

Replace `getLongBE()`with `self.get_long_be()`.
