### ISSUE TITLE
Support for burst files

### ISSUE THREAD

**Issue by jrk** [lclevy/canon_cr3#14]
Recent models (e.g., G7X-III & G5X-II) support high-speed raw bursts which are recorded in a single cr3 file. Is there any support for parsing and extracting these individual frames?

**Comment by lclevy** [comment]
Hi,
Could you please provide samples ?
Kind regards
Laurent

**Comment by jrk** [comment]
Here's a 6 frame one: https://www.dropbox.com/s/spx71id7qba1ee1/CSI_0031_01_06.CR3?dl=0

It is extracted from this larger (and more unwieldy) one: https://www.dropbox.com/s/k56tv2pf4cac5ik/CSI_0031.CR3?dl=0

**Comment by lclevy** [comment]
Very interesting, thank you!
how do you extracted these 6 frames ? in camera or using DPP ?

**Comment by lclevy** [comment]
should be fixed, no ?

**Comment by lclevy** [comment]
Fix confirmed

**Comment by Jip-Hop** [comment]
Can parse_cr3.py be used to extract individual raw images form a single raw burst image (roll)?

I don't have a camera that takes these raw bursts, but I've seen people make videos with them here: https://www.dpreview.com/forums/thread/4446141#forum-post-63360445

Currently they manually extract each image one by one using the Canon software, which is very time consuming.

If it can be done with parse_cr3.py, could you post an example of the command to use here? I'd love to let the peoples on dpreview know they no longer have to do it manually. Hopefully I'll see more of these videos in the future :)
