### ISSUE TITLE
Canon R3 Samples

### ISSUE THREAD

**Issue by oguruma1218** [lclevy/canon_cr3#23]
I have some R3 raw samples.
https://drive.google.com/file/d/1BH2HMqHvjLtVo2S_Nnf8selIOTa_V-5p/view?usp=sharing

**Comment by clanmills** [comment]
@oguruma1218 This is very helpful.  I added support for CR3 to Exiv2 last year.  May I ask invite you to share you link with Team Exiv2:  https://github.com/exiv2/exiv2

**Comment by lclevy** [comment]
Hi,
Thank you lot for these 132 raw and craw files! This is too much for me 😃, but @LebedevRI, @cytrinox @TurboGit will be happy ! One craw and one raw is usually enough for me. Thanks again 🙏

**Comment by lclevy** [comment]
May I ask please one dpraw and one heif from your R3 ?

**Comment by lclevy** [comment]
+ @Beep6581

**Comment by cytrinox** [comment]
Already integrated the samples into dnglab, thanks for contribution!

The R3 has no support for dual pixel (dpraw), but HEIF.

**Comment by kmilos** [comment]
@oguruma1218 Please upload a complete set (1 raw + 1 craw) to https://raw.pixls.us/, there is currently just a single raw (i.e. no matching craw).
