### ISSUE TITLE
Canon R7 HEIF

### ISSUE THREAD

**Issue by medemander** [lclevy/canon_cr3#26]
Hi,
I've got a sample for a Canon R7 HEIF if you're still looking for one
https://drive.google.com/file/d/1tBMZB5qwwQ_M0k4p_f7WF5z9VgSUaqzR/view?usp=share_link

**Comment by lclevy** [comment]
Thank you a lot!
Would you have a dual pixel raw?
And a raw with hdr ?

**Comment by medemander** [comment]
Sure thing, I put them in a Drive folder
https://drive.google.com/drive/folders/1aN7hIF_tHgeJgRFpLtOINujUsuxmITEk?usp=share_link

**Comment by lclevy** [comment]
🤩 thanks
Should I credit medemander ?

**Comment by medemander** [comment]
Yeah, medemander is fine. I'm glad I could help.
