### ISSUE TITLE
Canon R3 HEIF

### ISSUE THREAD

**Issue by johnbaro** [lclevy/canon_cr3#28]
I can provide R3 HEIF (or any other R3 outputs) if needed, just let me know what formats you'd like.

**Comment by lclevy** [comment]
Hi John,
Thank you for the offer!
What would be nice, please: HEIF, Dualpixel raw, craw+hdr and raw+hdr
Laurent

**Comment by lclevy** [comment]
Hi John, do you have time for samples please?

**Comment by johnbaro** [comment]
Hi @lclevy , my apologies, I didn't see this.
Yes, I can provide these next week.

**Comment by johnbaro** [comment]
Ok, I have HEIF, it doesn't look like the R3 does dual pixel, I've updated to the latest firmware and there's still no option in the menu.  
For the HDR files, there's a couple of options [HDR PQ](https://cam.start.canon/en/C010/manual/html/UG-03_Shooting-1_0070.html) and [HDR](https://cam.start.canon/en/C010/manual/html/UG-03_Shooting-1_0270.html).  

It appears that only HDR PQ is able to be captured RAW/CRAW, HDR just exports an HEIF (or should be an option for JPEG).

I'll upload CRAW+HDRPQ and RAW+HDRPQ and the HEIF, let me know if there's anything else you need.

**Comment by lclevy** [comment]
Hi John

"I'll upload CRAW+HDRPQ and RAW+HDRPQ and the HEIF, let me know if there's anything else you need."
That would be perfect, please

KR,
Laurent

**Comment by johnbaro** [comment]
Ok, this is now shared in onedrive, let me know if you want me to upload it somewhere else.

https://1drv.ms/f/s!An9WqALo-PvYlK1ZlK0tb1Sn2SZi8A?e=9PfZhd

**Comment by lclevy** [comment]
Thanks!
