### ISSUE TITLE
Canon R8

### ISSUE THREAD

**Issue by pdejl** [lclevy/canon_cr3#30]
Are you still looking for Canon R8 files?

**Comment by lclevy** [comment]
Yes, please, it would be great!
Raw, craw, heif and dual pixel if possible...
Kind regards,
Laurent

**Comment by pdejl** [comment]
Here it is: [https://fastshare.live/26205857/cnnr8.zip](url)
or
[https://cloud.fastshare.cz/share/get/07fIbJoHYZys6d5qNBJzmaczzftKXjbVhcKQf0snp5rMN4FMTpTZnTFVLlElmrNT](url)

Please let me know if you can download it/after you download it. Thx

**Comment by lclevy** [comment]
none worked. via dropbox or onedrive ?

**Comment by pdejl** [comment]
here on my Google drive: https://drive.google.com/file/d/1QwPCtbLEHtS-76ApMVsoBY9XCq_Bn04n/view?usp=share_link

**Comment by lclevy** [comment]
downloaded, thank you a lot! 
and files are well organized!
how do you want to be credited ? using github nickname ?

**Comment by pdejl** [comment]
Great!

Yes, please, credit on my GitHub nick will be very nice. Thank you.

I was glad to help and if you need more data from R8, just let me know...

Good luck with the project ;-)

**Comment by lclevy** [comment]
Maybe a raw with dust delete data?

**Comment by pdejl** [comment]
will do...

**Comment by pdejl** [comment]
here it is: https://drive.google.com/file/d/1moYsRM9O2L_WSK_-9sO-ZD_hGLVdiQpT/view?usp=sharing

I hope I did everything right and Dust Delete Data were appended to the RAW and CRAW...

**Comment by lclevy** [comment]
maybe one last with PQ=off, dual pixel off and HDR on (for cr3 format), please ?

**Comment by pdejl** [comment]
here it is: https://drive.google.com/file/d/1C7U0n1zkKAAurwnnaRZ6aaGJEcJi2ael/view?usp=sharing

Final image is always JPG, no matter what I select.

**Comment by lclevy** [comment]
There is an image to sample dust data (your jpeg?), then dust data is included as metadata : http://lclevy.free.fr/cr2/#ddd in jpeg or raw. 
Try exiftool -DustRemovalData pic.cr3

**Comment by pdejl** [comment]
Hi,
yes, dust delete data are included, because I made them for samples for you before and they cannot be deleted from camera, only updated, and as you said, they are always included in all JPG and RAW thereafter.

Did you download the last zip? I mean that PQ=off, dual pixel off and HDR on? Those pictures are not ONLY DDD, I just photographed light bed sheets which may look like DDD :-) I have to admin I am not sure what you mean with your latest comment: you can use exiftool on provided files as well...

Do you need any other data from R8?

**Comment by lclevy** [comment]
> here on my Google drive: https://drive.google.com/file/d/1QwPCtbLEHtS-76ApMVsoBY9XCq_Bn04n/view?usp=share_link

This one is downloaded, thanks. For other ones, I'm not at home yet

**Comment by lclevy** [comment]
> here it is: https://drive.google.com/file/d/1C7U0n1zkKAAurwnnaRZ6aaGJEcJi2ael/view?usp=sharing
> 
> Final image is always JPG, no matter what I select.

R5 does cr3 and HDR, maybe R8 does not...

**Comment by pdejl** [comment]
Yep, R8 does not, or I do not know how to achieve that. I have selected output final HDR image to be RAW only and it created JPG only. That is what I meant with "Final image is always JPG, no matter what I select."

**Comment by lclevy** [comment]
Hi,
> > here it is: https://drive.google.com/file/d/1C7U0n1zkKAAurwnnaRZ6aaGJEcJi2ael/view?usp=sharing
maybe this one expired?
Kind regards
Laurent

**Comment by pdejl** [comment]
Hi, I thought you already downloaded and deleted it. Here it is again:  https://drive.google.com/file/d/1TZAmrf1p84eIBpxCVlLkQNsO-YH7Xsmj/view?usp=sharing

(it is PQ=off, dual pixel off and HDR on)

**Comment by lclevy** [comment]
> Hi, I thought you already downloaded and deleted it. Here it is again: https://drive.google.com/file/d/1TZAmrf1p84eIBpxCVlLkQNsO-YH7Xsmj/view?usp=sharing
> 
> (it is PQ=off, dual pixel off and HDR on)

downloaded, thank you
