### ISSUE TITLE
Canon r6mk2 samples

### ISSUE THREAD

**Issue by swesemeyer** [lclevy/canon_cr3#33]
Do you still need samples from that camera?

It looks as if exiv2 cannot read the exif info in the raw file data but can read it in the craw format so there must be something new...

Happy to provide all sorts of samples.

**Comment by lclevy** [comment]
Hi, yes, please. Raw, craw, dpraw and heif.
And burst if possible

**Comment by swesemeyer** [comment]
Hi,

Please find the files here:

https://drive.google.com/drive/folders/1ljuaLbHA5FsHH02cwBCOSzuIIpipQq1c?usp=sharing

I hope they are labelled correctly...

If you need more or any other settings then let me know.

Cheers,
 Steve

**Comment by lclevy** [comment]
Thank you, I'll take a look Sunday evening CET.

**Comment by lclevy** [comment]
Perfectly ordered in directories, thank you!

**Comment by lclevy** [comment]
Finally updated the doc with proper credits :-)
