### ISSUE TITLE
R5m2 samples

### ISSUE THREAD

**Issue by piratenpanda** [lclevy/canon_cr3#37]
I recorded raw, craw and heif. It seems there is no dpraw option anymore compared to the R5 or I've been missing it. In case you need more samples let me know
https://www.pandainthecloud.de/nextcloud/index.php/s/qeMyi2sefdiYfjf

**Comment by lclevy** [comment]
Hi, thank you a lot. Can you please add a raw with electronic shutter (should be 12bits) and a jpg or raw with dust removal data ?

**Comment by piratenpanda** [comment]
should now be in the folder as well. But I thought ES is 14bit now

**Comment by lclevy** [comment]
readme updated
