### ISSUE TITLE
Full size JPG extraction

### ISSUE THREAD

**Issue by StefanOltmann** [lclevy/canon_cr3#38]
Hi there,

Thank you so much for your work in documenting this - it has been incredibly helpful!

Thanks to your efforts, I was able to add support for CR3 in [my metadata lib](https://github.com/ashampoo/kim). :)

However, I’m struggling to understand how to extract the full-sized preview from the mdat. Could you explain how to locate the offsets in a bit more detail?

I’m not very experienced with Python, so any extra guidance would be much appreciated.

Best regards,

Stefan

**Comment by lclevy** [comment]
Option -x
See https://github.com/lclevy/canon_cr3/blob/e2db91fc1df56afb887606fb68967ef9f2054408/parse_cr3.py#L346

**Comment by StefanOltmann** [comment]
Thank you! So I should go with co64.

How do I interpret these bytes? What datatype is it?

**Comment by lclevy** [comment]
Follow the code...

**Comment by StefanOltmann** [comment]
Got it. I'll look for a Python expert to help me figure out what needs to be done.

**Comment by lclevy** [comment]
Or learn some python 😉

**Comment by StefanOltmann** [comment]
Yeah, one day. Right now I try to learn how I must interpret the `co64` field.

**Comment by lclevy** [comment]
See base media file format document
